# basics
* ## condition
* ## loop
* ## function 
* ## دي كلها لغة python لو هنتستخدمها في اي تراك عندي

In [1]:
print("hello world")# ده امر بقدر من  خلاله ان user يشوف الناتج بتاعي 
print("Basant")
print("Basant")
print("Basant")
print("Basant")# هي المسئولة عن طباعه كلمة معينه في السيستم عندي انها تظهره لل user
print("Basant")#print ------ function حاجة بتنفذ حاجة معينه اكشن معين 
#data types
print("Basant")#string (Text)
print(5)#integer 1,2,3,...............
print(5.6)#float 3.6.............
print(True)#boolean----true or false

hello world
Basant
Basant
Basant
Basant
Basant
Basant
5
5.6
True

In [3]:
print(hello)#name 'hello' is not defined بمعني اني معنديش حاجة في اللغه اسمها hello ولكن عندي نوع من الداتا اسمه string

NameError: name 'hello' is not defined

In [2]:
print("basant",end="")#end----> parameter in function (feature function)-->calling 
#هي خاصة بقدر اني استدعيها واستخدمها ودي function جاهزة
print("Hala")

basantHala

In [1]:
print("basant",end="/")#end----> parameter in function (feature function)-->calling 
#هي خاصة بقدر اني استدعيها واستخدمها ودي function جاهزة
print("Hala")

basant/Hala

In [2]:
print("basant")
print("Hala")

basant
Hala

In [6]:
print("basant",end="/")
print("Hala",end="/")
print("omar")

basant/Hala/omar

In [11]:
print("basant","/","Hala\n")


print("basant/Hala")

basant / Hala

basant/Hala

In [3]:
type("basant")# function data type

str

In [2]:
print(type(5))

<class 'int'>

In [5]:
# comment الكود لا يراها بكتبه ك ملاحظات

In [13]:
#operator
10+10#sum
print(20+5)

25

In [15]:
10+10
5+5

10

In [16]:
print(20+5)
print(2+2)

25
4

In [17]:
10-5#sub

5

In [18]:
10*5#multiple

50

In [19]:
10%2#modules

0

In [20]:
10**2 #power

100

In [21]:
10/2#division

5.0

In [22]:
10//2#بيطلع رقم صحيح بس مش float (floor)

5

In [1]:
10%2 #check even بقدر اني احدد من خلالها الاعداد الزوجية التي تقبل القسمة علي 2 
# لو الناتج قابل القسمة يعني مطلعش منها رقم عشري =0

0

In [ ]:
5+1 # 5 ---> constant number
#6--->ناتج مقدرش اني استدعيه تاني هو مرمي كده هو له وظيفة واحدة انه يظهر ك ناتج مرمي وخلاص
#variable حل بقي المشكلة اللي عندي دي

In [3]:
#variable > store اقدر اني اخزن قيم من خلاله وvariable اني اغير قيم 
x=8
print(x)
print(type(x))

8
<class 'int'>

In [4]:
z="eldemoksy"
print(z)

eldemoksy

In [5]:
f=4.5
print(f)
print(type(f))

4.5
<class 'float'>

In [7]:
x=10#store
x+3#variable
x+5

15

In [11]:
x=1
print(x+3)
print(x+5)

4
6

In [13]:
x=10
z=x+3
print(z+5)

18

In [14]:
x#بيجيب اخر قيمة اتعملها run

10

In [15]:
c=1#define
c=2#update
c=4#update
c=10#update
print(c)

10

In [16]:
c

10

In [21]:
name="basant"
print(name)
type(name)
print(type(name))

basant
<class 'str'>

In [19]:
type(name)

str

In [22]:
name="basant"
print(name)

print(type(name))#لو هتحط اكتر من حاجة ف لازم تحط print علشان كده هيطبع اخر حاجة انت عملتها
type(name)

basant
<class 'str'>

str

In [24]:
#الممنوعات في تسميه ال variable
# 4x="hala"
# frist-name=
#frist  name=
#class=   buildin python
frist_name="mohammed"
print(frist_name)
x1=1
print(x1)

mohammed
1

In [31]:
x=2
x=x+10#math xxxxx or programming true

x

12

In [32]:
x=1
x+=10#math xxxxx or programming true
x

11

In [33]:
x=1
x-=10#math xxxxx or programming true
x

-9

In [34]:
x=10
x*=2
x

20

In [35]:
x=10
x%=2
x

0

In [36]:
x=10
x//=2
x

5

In [37]:
x=10
x/=2
x

5.0

In [38]:
x=2
y=2*x
z=2*x+y#equation
z

8

In [44]:
full_name="basantShaker"#كل char بياخد 1 byte =8bi
 # index        0123456789101112   
# انا بمشي ال STORE مش عشوائي انا بمشي بالترتيب ف بتساعدني في التخزين 
#لو خونتهم بنظام هعرف اني استدعيهم بردوا بنظام
print(full_name)

print(type(full_name))
print(len(full_name))#lenght طول الحروف بتاعتك اي غير انه كمان بيحسب المسافة ك حرف

basantShaker
<class 'str'>
12

In [41]:
max(full_name)# using ASCII code (American Standard Code for Information Interchange)
#اي رمز او حرف بيبقي مربوط كل حرف بارقام معينه binary في جدول ثابت

't'

In [45]:
min(full_name)

'S'

In [50]:
full_name.index("s")#index-->location

2

In [51]:
name.count("s")#number of character 
#الحرف ده موجود كام مرة عدد مرات تكرراه 
#python sensetive يعني حساس وبيفرق بين S , s

1

In [68]:
name="basant      "
print(name)#بستخدمها لو هطبع كذا حاجة في نفس المكان
print(type(name))#iهيجيب نوع المتغير
print(max(name))#ASCII code
print(min(name))
print ( name . index ('t') ) #العد من الصفر بتجيب مكانه فين انا بخون بالترتيب
print (name.count('a'))#عدد تكراره كام مرة 
print (name.count('  '))

basant
<class 'str'>
t

5
2
3

In [1]:
#()---> brackets
#[]--->square brackets
#{}--->dictionary or crealy brackets
input()#no calling

 basant

'basant'

In [2]:
name=input()

 bbb

In [3]:
print(name)
print(type(name))

bbb
<class 'str'>

In [5]:
full_name=input("enter your name :")
print(full_name)
print(type(full_name))

enter your name : gt

In [11]:
age=int(input("enter your age name :"))#input بتتعامل مع كل اللي بيدخلها كانه string
print(age)#varible بياخد اي data type بيتاع القيمة اللي بحطها له
print(type(age))

enter your age name : 24

24
<class 'int'>

In [9]:
fname=input("enter your frist name:")#default string
Lname=input("enter your last name:")
print("hello",fname,Lname)

enter your frist name: nn
enter your last name: jjj

hello nn jjj

In [12]:
a=bool(input("enter your age name :"))#input بتتعامل مع كل اللي بيدخلها كانه string
print(a)#varible بياخد اي data type بيتاع القيمة اللي بحطها له
print(type(a))

enter your age name : True

True
<class 'bool'>

In [ ]:
# function data type
#int()
#float()
#str()
#bool()

a=float(input("enter your age name :"))#input بتتعامل مع كل اللي بيدخلها كانه string
print(a)#varible بياخد اي data type بيتاع القيمة اللي بحطها له
print(type(a))

In [2]:
#حساب عمر شخص
year=int(input("enter your birthday :"))
now=2026
result=now-year
print("your age is: " ,result)

enter your birthday : 25

your age is:  2001

In [3]:
year

25

In [9]:
# data containers --> store one or more element
# tuple() tuple or barket
#list[]square bracket
# dictionary{:}كيرلي بيريسس
# set{}كيرلي بركتس

In [11]:
x=5,8
print(x)
print(type(x))

(5, 8)
<class 'tuple'>

In [ ]:
x=5,8
print(x)
print(type(x))#type as a data type

In [15]:
tup=("ahmed",4,3.4,True)# جواه اكتر من نوع ف بيرجع نوع container بتاعها
#index 0     1 2     3  or indes
print(tup[0])#tuple of zero

print(tup)
print(type(tup))

ahmed
('ahmed', 4, 3.4, True)
<class 'tuple'>

In [21]:
num=(1,2,3,4,5,6,7,8,9,10)
 #               -3  -2   -1
print(num[-3:-1])#لازم اكتب الصغير الاول وبعدين في stop بكتب الرقم الاكبر منه
print(num[-1:-3])
print(num[9])
#لا يوجد حاجة اسمها array في بايثون 
#array موجودة بس في numpy
#fexied size and data type عنده مرونه في المساحة وبحط اي نوع موجود عندي في اللغه
#slicing بتجيب عدد من الارقام مش رقم واحد وبحدد ليها بداية ونهاية 
print(num[1:6])# start:stop يعني ال index اللي هيوفق عنده مش ال end

(8, 9)
()
10
(2, 3, 4, 5, 6)

In [20]:
num[0:15]

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [9]:
num=(1,1,1,1,2,3,4,5,6,7,8,9,10) #هو مش flexible
# بمعني اني مقدرش وانا بضيف رقم احدد مكانه فين في النص في الجنب علي الطرف لا مش بقدر
print(len(num))
print(max(num))
print(min(num))
print(sum(num))
print(num.count(1))
print(num.index(1))
#بيشوف اول قيمة تقابله في حالة التكرار العنصر
print(num[5:9])
#slicing

13
10
1
58
4
0
(3, 4, 5, 6)

In [10]:
#tuple Use
num1=num+(100,200,300)
num1

(1, 1, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 100, 200, 300)

In [21]:
num2=(70,60,50)+num
print(num2)
#not flexible

#fast access
x= 4,3
print(x)
#بالرغم اني محددتش له انهي continer ف هة حدد انها tuple
#fast creat
#usage : coordinates
#محاور X,y ---> (5,7)بتعبر عن Location النقاط بال tuple

(70, 60, 50, 1, 1, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
(4, 3)

In [19]:
num2 = (1,2,3) + (5,6,7)# بتعمل اتحاد 
num2
#اضيف رقم عن طريق ال index غير وجو

(1, 2, 3, 5, 6, 7)

In [23]:
#'طلعت ال list علشان احل مشاكل ال tuple من فكرة الحذف والاضافة 
l=["ahmed",1,True,2.4]#متنوعه ممكن احط فيها كذا عنصر 
#   0       1  2   3
print(l[0])
# flexibility
print(l)
print(type(l))

ahmed
['ahmed', 1, True, 2.4]
<class 'list'>

In [41]:
n=[1,2,3,4,5,6,7,8,9,10]
#functions 
print(len(n))
print(max(n))
print(min(n))
print(type(n))
print(n.index(10))
print(n.count(10))
n.append(11)#add number وwithout index
print(n)#بتضيف في الاخر

#اتزحزح شوية 
n.insert(3,113)# (index or location,values)بضيف العنصر ومكانه فين تحديجا مش بتتبدل هي بس بتغير الترتيب وال index
print(n) 


n.remove(11)# delet element
print(n)
#حذف عن طريق ال location
n.pop(3)#cut element
print(n)
x=n.pop(9)
print(x)#يعني مش بيتعمله حذف نهائي ده هو بيتخزن لسه في الذاكرة وانا حطيت متغير علشان ابين انه بيتخزن
a=[1,2,3,4,5]
a.pop()
print(a)
#تلقائي هيشيل اخر رقم\

#بيعكس الارقام
n.reverse()
print(n)
#بيرتب
s=[3,1,2,3,7,6,5]
s.sort()
print(s)

n.extend([500,600])#add list to list 
#بتضيف list علي list بتاعتك بمعني اصح اقدر اضيف اكتر من عنصر عندي
print(n)



#;كده اخدت نسخة كوبي وحطيتها في متغير تاني
copy=n.copy()
print(copy)


n.clear()

print(n)
#list عبارة عن عمود موجود في جدول

10
10
1
<class 'list'>
9
1
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[1, 2, 3, 113, 4, 5, 6, 7, 8, 9, 10, 11]
[1, 2, 3, 113, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
10
[1, 2, 3, 4]
[9, 8, 7, 6, 5, 4, 3, 2, 1]
[1, 2, 3, 3, 5, 6, 7]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 500, 600]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 500, 600]
[]

In [42]:
n.pp()

AttributeError: 'list' object has no attribute 'pp'

In [7]:
#dictionary {:} كيرلي brackets
dic= {"key" : "value"}
  #    DR   : ahmed
#      eng  : youssef
#      Name : basant


user1={"name":"basant",
       "age":25, 
       "college":"engineering"
      }


print(user1)
print(type(user1))
    

#list calling use index 
#dictionary calling use key
print(user1["name"])

{'name': 'basant', 'age': 25, 'college': 'engineering'}
<class 'dict'>
basant

In [8]:
user1[0]#dictionary not calling use index

KeyError: 0

In [2]:
lis=["a","b","c"]
print(lis[0])

a

In [8]:
u={"name":"basant",
       "age":25, 
       "college":"engineering"
      }

#list عبارة عن عمود في الجدول
#dictionary عبارة عن الجدول نفسه
#عبارة عن مجموعه من colunms
#بدل اما اربط كل قيمة ب index لا الربط هنا بيبقي بال key

print(u)
print(type(u))
print(len(u))#key =value بيتعبرهم حاجة علي بعضها ف انا عندي 3
print(u.keys())
print(u.values())
print(u.items())#بيرجع list فيها كل ده 
u.update({"A" : 5})#= extend
print(u)

{'name': 'basant', 'age': 25, 'college': 'engineering'}
<class 'dict'>
3
dict_keys(['name', 'age', 'college'])
dict_values(['basant', 25, 'engineering'])
dict_items([('name', 'basant'), ('age', 25), ('college', 'engineering')])
{'name': 'basant', 'age': 25, 'college': 'engineering', 'A': 5}

In [6]:
u.update({"A" : 5})#add dictionary to dictionary
#{} بتعبر عن dictionary
#add new key and value
u
  #update in dictionary = extend in list

{'name': 'basant', 'age': 25, 'college': 'engineering', 'A': 5}

In [25]:
num=[1,2,3,4,5]
num.extend([5,5,5,5,5,5])
num

[1, 2, 3, 4, 5, 5, 5, 5, 5, 5, 5]

# User
print(num.extend([1,2,3,4,5,6,6,6])

In [30]:
print(u.get("Name"))

None
basant

In [28]:
print(u.get("name"))#بتجيب value عن طريق key ولكن هي عاملة زي جملة if لو مفيش قميمة ممكن ترد none او بالجملة اللي انا هكتبها
print(u["name"])

basant

In [29]:
print(u.get("Name","not found"))#option message في حالة انه ملقاش القيمة بتاعتك

not found

In [32]:
u.pop("A")

5

In [34]:
x=u.pop("name")
x#cutting

'basant'

In [35]:
u.popitem()#بتشيل اخر حاجة 
#cut to the last item

('college', 'engineering')

In [3]:
z=u.copy()
z

{'name': 'basant', 'age': 25, 'college': 'engineering'}

In [5]:
x=u.clear()
x

In [6]:
u

{}

In [7]:
z

{'name': 'basant', 'age': 25, 'college': 'engineering'}

In [24]:
dic={"Name":"basant",
    "age":25,
    "collage":"mansoura"
    }
print(dic)

{'Name': 'basant', 'age': 25, 'collage': 'mansoura'}

In [31]:
dic["Name"]="rana"#update one value
print(dic)
dic["address"]="mansoura"#add one values
#= function update
#dic.update({"address":"mansoura"})
print(dic)
dic.update({"a":23,"b":22})#new dictionary
#add one or  more values
print(dic)
dic.update({"Name":23,"b":23})#update one or more values
print(dic)

{'Name': 'rana', 'age': 25, 'collage': 'mansoura', 'address': 'mansoura', 'a': 23, 'b': 23}
{'Name': 'rana', 'age': 25, 'collage': 'mansoura', 'address': 'mansoura', 'a': 23, 'b': 23}
{'Name': 'rana', 'age': 25, 'collage': 'mansoura', 'address': 'mansoura', 'a': 23, 'b': 22}
{'Name': 23, 'age': 25, 'collage': 'mansoura', 'address': 'mansoura', 'a': 23, 'b': 23}

In [ ]:
#CSV/Json file
#json:Dictionary  at json file and collection of dictionary and support datatypes and used in appliction 
#CSV--->excel Table  and used in excel
#different excel file and CSV files---> csv بيكون بسيط جدا مفيش اي equation ,flat file
#excel بيكون no flat في اكتر من table,يوجد فيه equations(average ,mean,max,min....),ده فايل عادي اكسيل 
#csv بيشيل داتا ابسط من 
#json متداخل 
#csv-->بيبقي منظم اكتر
#CSV--->شكله عبارة عن دول في excel
#csv-->بتتكون من row and colums 
#بتتعامل مع البابل شيت 
#data visiluazations بتتعامل مع البرامج اللي بتتعامل مع
#such as powerBI
#تتصل ب ,
#مش بتتعامل مع كل لغات البرمجة 
#

In [7]:
#Tables
     #colums       rows
dic={"Name":["basant","rana","ahmed","hala"],
    "age":[22,23,24,6]}
print(dic)

{'Name': ['basant', 'rana', 'ahmed', 'hala'], 'age': [22, 23, 24, 6]}

In [8]:
import pandas as pd
df=pd.DataFrame(dic)
df

     Name  age
0  basant   22
1    rana   23
2   ahmed   24
3    hala    6

In [27]:
# just an one user ----->json file
dic1={"name":"hala",
      "age":6}
# a table
dic2={"name":["bbbb","eldemoksy"],
      "age":[22,23]}


#tables
dic3={
    "Hr" : { "Name":["ahmed","ali"],
     
             "age":[22,23]},
    "sales":{ "xx":["ahmed","ali"],
     "aaa":[22,23]},  
    "customer":{ "N":["ahmed","ali"],
     
             "a":[22,23]},
     }
dic3

{'Hr': {'Name': ['ahmed', 'ali'], 'age': [22, 23]},
 'sales': {'xx': ['ahmed', 'ali'], 'aaa': [22, 23]},
 'customer': {'N': ['ahmed', 'ali'], 'a': [22, 23]}}

In [26]:
import pandas as pd
df=pd.DataFrame(dic3)
df

                Hr         sales      customer
Name  [ahmed, ali]           NaN           NaN
age       [22, 23]           NaN           NaN
xx             NaN  [ahmed, ali]           NaN
aaa            NaN      [22, 23]           NaN
N              NaN           NaN  [ahmed, ali]
a              NaN           NaN      [22, 23]

In [28]:
dic3["Hr"]["Name"]

['ahmed', 'ali']

In [1]:
#set{} اقواس المجموعه
# بتشيل التكرار
#unique valued - sorting
sets={1,2,2,2,2,2,2,3,4,5}
print(sets)

{1, 2, 3, 4, 5}

In [4]:
l1=[1,2,2,22,2,2,2,4]
print(set(l1))
set([1,1,1,1,1,1,1])

{1, 2, 4, 22}

{1}

In [3]:

set1={1,2,3}
set2={3,4,5}
r1=set1|set2
print(r1)

{1, 2, 3, 4, 5}

In [8]:
#union / intersection / differences
#union
set1={1,2,3}
set2={3,4,5}
union =set1|set2
print(union )
#  intersection 
# المشترك
intersection =set1&set2
print(intersection )
#differences
difference1=set1-set2
#اللي موجود في set1 ومش موجود في set2 
print(difference1)
#اللي موجود في الاول ومش موجود في التاني
differences=set2-set1
print(differences)
#المشترك مش بيتحط

{1, 2, 3, 4, 5}
{3}
{1, 2}
{4, 5}

In [9]:
num=input("enter your number :")
print(num)
print(type(num))

enter your number : 1.2

1.2
<class 'str'>

In [10]:
num=float(input("enter your number :"))
print(num)
print(type(num))

enter your number : 1

1.0
<class 'float'>

In [17]:
a="basant Shaker"
print(a.split()) #separat depend on space
A="basantShaker"
print(A.split())#separat depend on space
b="basant_Shaker"
print(b.split("_"))#separat depend on _ or - or * ot /
B="basantxShaker"
print(b.split("x"))#لما بحط اي حرف بيحط ل _

['basant', 'Shaker']
['basantShaker']
['basant', 'Shaker']
['basant_Shaker']

In [21]:
num1=input("enter a list of number :")
print(num1.split())

enter a list of number : 22222

['22222']

In [1]:
num2=input("enter a list of number :").split()

num2

enter a list of number : 1 2 3

['1', '2', '3']

In [2]:
num2=int(input("enter a list of number :").split())


num2

enter a list of number : 1

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'

In [3]:
int("5")

5

In [4]:
int(["1","2"])# مش هتقدر تحول list من الstring الي number

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'

In [6]:
# map عن طريقها عندي دالة int مش بتطبق غير علي  قيمة واحدة او string واحد ف عاوزة اعملها زي loopاني بكرر الدالة دي اكتر من مرة علي نفس list 
# بتمابها اني بعدها علي element by element
#["5","4"]---> iterable 
#int----->fubction 
#map(fun,iterable)

x=map(int,input("enter a list of numbers:").split())
x# return location in memory

enter a list of numbers: 1 2 3 4 5

In [15]:
x= list(map(int, input ("enter alist of numbers:").split()))
       
# هنا بقوله مترجعليش المكان اللي في الذاكرة ورجلي list
x# return location in memory
z=sum(x) 
print(z)

enter alist of numbers: 1 , 2, 3

ValueError: invalid literal for int() with base 10: ','

In [12]:
#coditional statment 
if condition:
    action #عندي حدوث حدث معين بمعني اوضضح عندما condition يتحقق هخش انفذ action

In [2]:
if True:
    print("hello")

hello

In [1]:
if False:#fale معاناه انك مش هتنفذ
    print("hello")#؟؟

In [4]:
print(10==10 )#is equal
if 10==10:
    print('yes')

True
yes

In [5]:
age =18
if age>=18:#True
    print("you are an adult")

you are an adult

In [ ]:
age =9
if age>=18:#return false
    print("you are an adult")

In [8]:
age =int(input("enter your age:"))
if age>=18:#return True or false 
    print("you are an adult")
else:
    print("your are a minor")

enter your age: 2

your are a minor

In [9]:
grade=int(input("enter your grade"))

if grade>=85:
    print('A')
if grade>=75:
    print('B')
if grade>=65:
    print('C')
else:
    print('D')

enter your grade 99

A
B
C

In [10]:
grade=int(input("enter your grade"))

if grade>=85:
    print('A')
elif grade>=75:
    print('B')
elif grade>=65:
    print('C')
else:
    print('D')

enter your grade 100

A

In [2]:
age=18
register=True 
if age>=18 & register:
    print("Yes")

Yes

In [6]:
age=18
register=True 
#   True          True
if age>=18 and register:#codition 1--->True & condition2--->True
    print("you can vote")
else:
    print("you can not vote")

Yes

In [11]:
age=18
register=False 
#   True          True
if age>=18 and register:#codition 1--->True & condition2--->False
    print("you can vote")
else:
    print("you can not vote")#ده الشرط اللي هيتنفذ

you can not vote

In [9]:
age1=1
register1=True 
#   True          True
if age1>=18 or register1: #or ---> at least one conditions achieve
    print("Yes")

Yes

In [14]:
age1=18
register1=False
#   True          ومش register
if age1>=18 and not register1: #codition 1--->True & condition2--->False ده شرك علشان يتبطع yes
    #and not ---> يعني الاول متحققه والتانية مش متحققه الناتج هيطلع ب True
    #True+false=True
    print("Yes")  
  # بمعني ان false دي بتححقق الشرط بتاعي ف false هترد علي ب True

Yes

In [15]:
age=18
register=False 
#   True         ( True)يعني علشان تحقق register متبقاش 
if age>=18 and not register:#codition 1--->True & condition2--->False
    print("you can vote")
else:
    print("you can not vote")#

you can vote

In [16]:
age=18
register=True 
#   True         ( True)يعني علشان تحقق register متبقاش 
if age>=18 and not register:#codition 1--->True & condition2--->False
    print("you can vote")
else:
    print("you can not vote")#بتثبت اللي قبلها وتنفي اللي بعدها

you can not vote

In [18]:
#inputs user
user=input("enter your username")
password=input("enter your password")

#system DB
userSystem="admin"
passwordSystem="A1234"

if user==userSystem and password==passwordSystem:
    print("you login successfully")
else:
    print("Invaild username and password")

enter your username admin
enter your password A1234

you login successfully

In [20]:
#Nested If statment

#inputs user
user=input("enter your username")
password=input("enter your password")

#system DB
userSystem="admin"
passwordSystem="A1234"
#هو هنا لو اليوزر نيم عندي غلط هيطبع
#Invalid username"
#طب لو صح هيخش يشوف الباسورد عندي لو صح يطبع you login successfully
#ولو غلط هيطبع"Invalid password
# يعني هو مش هيخش لل باسورد غير لما يتاكد ان username شغال
if user==userSystem:
    if password==passwordSystem:
        print("you login successfully")
    else:
        print("Invalid password")
else:
    print("Invalid username")

enter your username efgr
enter your password A1234

Invalid username

In [23]:
#Nested If statment
#هي نفسها بس ضفت شرط في حالة لو الاتنين عندي غلط
#inputs user
user=input("enter your username")
password=input("enter your password")

#system DB
userSystem="admin"
passwordSystem="A1234"

if user==userSystem or password==passwordSystem:
  if user==userSystem:
      if password==passwordSystem:
           print("you login successfully")
      else:
        print("Invalid password")
  else:
       print("Invalid username")

else:
    print("Invaild username and password")

enter your username jij
enter your password A1234

Invalid username

In [1]:
lis=[1,2,3,4,5]
if 5 in lis:
    print('yes')
else:
    print('No')

yes

In [ ]:
range(start ,stop,step)

In [10]:
print(list(range(0,10,1)))
print(list(range(0,10)))#step default-->1
print(list(range(0,10,2)))#step=2
print(list(range(10)))#start default-->0  #stop -->10   #step default-->1
#print(list(range(0,10,1)))==print(list(range(0,10)))==print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8]

In [11]:
print(list(range(0,10,1)))==print(list(range(0,10)))==print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

True

In [12]:
range(0,10,1)==range(0,10)==range(10)

True

In [1]:
lis=[1,2,3,4,5]

#print element by element
print(lis[0])
print(lis[1])
print(lis[2])
print(lis[3])
print(lis[4])
#XXXXX مش محقق clean code
#using for loop ---->clean code
#repeat print
#looping --->for loop or while loop

1
2
3
4
5

In [2]:
lis=[1,2,3,4,5]
#   الباب 
#x-->pointer
#لما list تخلص يبقي loop عندي خلص
for x in lis:
    #x--->بيلف علي كل عنصر وبيقف عليه وكل عنصر عندي xبتقف عليه وبتشوف انت عاوزة اي من العنصر ده
    print(x)

1
2
3
4
5

In [3]:
lis=[1,2,3,4,5]
#   الباب 
#x-->pointer
#لما list تخلص يبقي loop عندي خلص
for x in lis:
    #x--->بيلف علي كل عنصر وبيقف عليه وكل عنصر عندي xبتقف عليه وبتشوف انت عاوزة اي من العنصر ده
    print(x**2)#ضرب كل عنصر في 2 
    #بمعني ان من خلال ال foor loop اقدر اني اعمل equation

1
4
9
16
25

In [4]:
lis=[1,2,3,4,5]
#كل عنصر هيقف عليه اسمه x
#   الباب 
#x-->pointer
#لما list تخلص يبقي loop عندي خلص
for x in lis:
    #x--->بيلف علي كل عنصر وبيقف عليه وكل عنصر عندي xبتقف عليه وبتشوف انت عاوزة اي من العنصر ده
    print(x+2)

3
4
5
6
7

In [5]:
lis=[1,2,3,4,5]
for x in lis:
    print(x//2)

0
1
1
2
2

In [6]:
lis=[1,2,3,4,5]
for x in lis:
    print(x/2)

0.5
1.0
1.5
2.0
2.5

In [7]:
lis=[1,2,3,4,5]
for x in lis:
    print(x*5)

5
10
15
20
25

In [8]:
#ممكن اني اعمل loop علي 
#string 
#integer
#float
#boolean
#هو بيتعامل معاها انها عنصر وليها index 


x=['mariam','hala','aliaa','omar']
for i in x:
    print(x)
    #هعتبر عن list كلها عبارة عن عنصر واحد

['mariam', 'hala', 'aliaa', 'omar']
['mariam', 'hala', 'aliaa', 'omar']
['mariam', 'hala', 'aliaa', 'omar']
['mariam', 'hala', 'aliaa', 'omar']

In [9]:
x=['mariam','hala','aliaa','omar']
for i in x:
    print(i)

mariam
hala
aliaa
omar

In [10]:
x=['mariam','hala','aliaa','omar']
for i in x:
    print(len(i))
    #هيطبع عدد حروف كل اسم

6
4
5
4

In [12]:
x=['mariam','hala','aliaa','omar','b']
for i in x:
    print(len(x))
      #هعتبر عن list كلها عبارة عن عنصر واحد
    #هطبع عندي كل اسم في ال listعلي حسب كم اسم عندي
    #لو عندي 5 اسماء هتطبع 5 و5 مرات
    #6 اسماء هيطبع 6 ,6مرات

5
5
5
5
5

In [13]:
x=['mariam','hala','aliaa','omar']
for i in x:
    print(max(i))#ascii code

r
l
l
r

In [15]:
x=['mariam','hala','aliaa','omar']
for i in x:
    print(i,"the lenght of it:",len(i))
    #هطيبع الاسم وطوله قد اي

mariam the lenght of it: 6
hala the lenght of it: 4
aliaa the lenght of it: 5
omar the lenght of it: 4

In [16]:
x=['mariam','hala','aliaa','omar']
#    0       1      2        3-->index
#loop on element or index

for i in x:#loop on element
    print(i)

mariam
hala
aliaa
omar

In [18]:
x=['mariam','hala','aliaa','omar']
#    0       1      2        3-->index
#loop on element or index

for i in range(len(x)):#loop on index of element
    print(i)
#هنا هو اللي شاف ال list وعدهم
    #في الحالة دي ممكن مبقاش عارف العنصر بس انا عارف location بتاعه

0
1
2
3

In [22]:
len(x)
#range---->بيطلع ارقام بس

4

In [20]:
x=['mariam','hala','aliaa','omar']
#    0       1      2        3-->index
#loop on element or index
#هنا عد الارقام طلع نفس النتايج ولكن ملفش علي list نفسها
for i in range(4):#loop on index of element
    print(i)

0
1
2
3

In [21]:
x=['mariam','hala','aliaa','omar']
#    0       1      2        3-->index
#loop on element or index

for i in range(5):#loop on index of element
    print(i)

0
1
2
3
4

In [2]:
x=['mariam','hala','aliaa','omar']
#    0       1      2        3-->index
#loop on element or index

for i in range(len(x)):#loop on index of element
    print(i,x[i])

0 mariam
1 hala
2 aliaa
3 omar

In [4]:
#formatting string
x=7
#هستخدم اقواس ال dictionary
#f هتعرف ان xدي variable 
#هتفهم انك عاوزة تطبع ال value بتاعتها
print(f"x is equal {x}")

x is equal 7

In [5]:
#example 
fname="basant"
lname="shaker"
#f---->بتروح ل قيمة ال variable وبتجيبها 
print(f"the frist name is {fname} and the last name is {lname}")

the frist name is basant and the last name is shaker

In [6]:
#even and odd
#even ----> زوجي [2,4,6,8,10]
#odd--->[1,3,5,7,9]فردي
x=[1,2,3,4,5,6,7,8,9,10]
#for looping 
for i in x:
    if i%2==0:#تبقبل القسمة علي 2
        print(f"{i} is even")
    else:
        print(f"{i} is odd")

1 is odd
2 is even
3 is odd
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is odd
10 is even

In [7]:
x=[1,2,3,4,5,6,7,8,9,10]
even=[]
odd=[]
#for looping 
for i in x:
    if i%2==0:#تبقبل القسمة علي 2
      even.append(i)
    else:
       odd.append(i)
print(f"even number :{even}")    
print(f"even number :{odd}")

even number :[2, 4, 6, 8, 10]
even number :[1, 3, 5, 7, 9]

In [ ]:
x=input("enter your numbers")
even=[]
odd=[]
#for looping 
for i in x:
    if i%2==0:#تبقبل القسمة علي 2
      even.append(i)
    else:
       odd.append(i)
print(f"even number :{even}")    
print(f"even number :{odd}")

In [12]:
x=int(input("enter your numbers"))#1 2 3 4 5كلها علي بعضها
even=[]
odd=[]
#for looping 
for i in x:
    if i%2==0:#تبقبل القسمة علي 2
      even.append(i)
    else:
       odd.append(i)
print(f"even number :{even}")    
print(f"even number :{odd}")

enter your numbers 123

TypeError: 'int' object is not callable

In [ ]:
x=5
print(type(x))

In [1]:
xx= list(map(int,input("enter yur numbers:").split()))
#سبب ان استخدام mapping اني
#علشان int مش هتتقبل فكرة ان اضيف function -->split
#map وظيفتها بتماب علي كل رقم وتطبق عليها انه يتحول ل int
even=[]
odd=[]
#for looping 
for i in xx:
    if i%2==0:#تبقبل القسمة علي 2
      even.append(i)
    else:
       odd.append(i)
print(f"even number :{even}")    
print(f"even number :{odd}")

enter yur numbers: 1 2 3 4

even number :[2, 4]
even number :[1, 3]

In [3]:
xx= map(int,input("enter yur numbers:").split())
#سبب ان استخدام mapping اني
#علشان int مش هتتقبل فكرة ان اضيف function -->split
#map وظيفتها بتماب علي كل رقم وتطبق عليها انه يتحول ل int
even=[]
odd=[]
#for looping 
for i in xx:
    if i%2==0:#تبقبل القسمة علي 2
      even.append(i)
    else:
       odd.append(i)
print(f"even number :{even}")    
print(f"even number :{odd}")

enter yur numbers: 1 2 3 4 5 6

even number :[2, 4, 6]
even number :[1, 3, 5]

In [5]:
lis=map(int,input("enter your number").split())
#عاوزة اطلع even ,odd , عددهم, مجموعهم
#even
even=[]
even_count=0
even_sum=0

#odd

odd=[]
odd_count=0
odd_sum=0


for i in lis:
    if i%2==0:
        even.append(i)
        even_count+=1#عددهم عندي كام عنصر 
        even_sum+=i
    else:
        odd.append(i)
        odd_count+=1
        odd_sum+=i

print(f"even list={even},count of even={even_count},sum of even={even_sum}")
print(f"even list={odd},count of even={odd_count},sum of even={odd_sum}")

enter your number 1 2 3 4

even list=[2, 4],count of even=2,sum of even=6
even list=[1, 3],count of even=0,sum of even=4

In [7]:
numbers=[1,2,3,4,5,6,7,8,9,10]

for i in numbers:
    if i==5:
        break
    else:
        continue#أول ما بيشوف الـ continue بيطير للّفة التالية وبيتجاهل تماماً أي سطر مكتوب بعدها
        print(i)#هنا مش هيشوف السطر ده ويطبع

In [4]:
numbers=[1,2,3,4,5,6,7,8,9,10]

for i in numbers:
    if i==5:#stop
        break
    else:
    
        print(i)
        continue
        #أول ما بيشوف الـ continue بيطير للّفة التالية وبيتجاهل تماماً أي سطر مكتوب بعدها
         # break----->stop code 
        #  continue--->skip and   continue

1
2
3
4

In [5]:
numbers=[1,2,3,4,5,6,7,8,9,10]

for i in numbers:
    if i==5:
        break
    else:
    
        print(i)

1
2
3
4

In [8]:
numbers=[1,2,3,4,5,6,7,8,9,10]

for i in numbers:
    if i==5:
        continue# skip 5 and continue 
        #يعني الشرط متححق لو اتحقق هيخش يشوف اها لاقيت continue --->skip
        #مش هنعطل ولا اكننا شايفنوا استمر BASMALA
    else:
    
        print(i)

1
2
3
4
6
7
8
9
10

In [9]:
numbers=[1,2,3,4,5,6,7,8,9,10]

for i in numbers:
    if i==5:
        pass# skip such as continue
        #pass----->ولكن ليها امكانيات اكتر
        #pass----->ممكن استخدمها في امكان غير loop لكن continue لااااااااااااااااا
        #ممكن اعمل من خلالها skip for error
        #pass----->ممكن اني استخدمها في function
        #continue----->لااااااااااااااااااااايمكن اني استخدمها في function
        #continue---->skip for condition
    else:
    
        print(i)

1
2
3
4
6
7
8
9
10

In [2]:
lis=[1,2,3,4,5,6,7,8,9]

for i in lis:
     if i%2==0:#print even
       print(i)
     else:
         continue#skip odd

2
4
6
8

In [5]:
#nested list----->access number ---->need nested loop

number =[[1,2],[3,4]]
#         i      i
#هو دخل جو ال list []اعتبر ال list اللي جواها element واحد
#[1,2]-----> one element --->i
#[3,4]---->one element ------->i
# عمل print ليها كانها عنصر واحد
for i in number:
    print(i)

[1, 2]
[3, 4]

In [8]:
#nested list----->access number ---->need nested loop
#problem sole

number =[[1,2],[3,4]]
 #ماهو ال i هتخش علي كانها عنصر عاوزة بقي حاجة تجيب اللي جوه جوه [1,2]
    #عاوزة حل يجيب اللي مابين السطور 
for i in number:
    print(i)
    for j in i:
         print(j)


#اول مرة جاب [1,2]
#دخل علي [1,2]وجاب كل عنصر ل واحدة

#   تاني مرة جاب [3,4]
#دخل علي [3,4]وجاب كل عنصر ل واحدة

[1, 2]
1
2
[3, 4]
3
4

In [ ]:
#for loop---->استخدمتها اكتر من while loop

#while ------>طول اما هي ب true هتفضل مستمرة
#while ------> return false --->stop
#while ------>merge betwwen for loop and if condition
#while or if ان while اسمها while loop يعني بتلف 
#if codition ----->بتخش تحقق شرط واحد وخلاص 
#while loop------>بتخش تحقق اكتر من شرط عندي
#while شبه for انها بتلف زيها بس بتلف علي شرط يعني طول اما الشرط ده ب true هتفضل مكملة 
#for loop ---->لما ال list بتخلص هي بتوقف او لو حطيت شرط
i=0

while i<=5:
    print(i)
    i+=1

In [1]:
i=0
if i<=5:
    print(i)
    i+=1

0

In [6]:
i=0
even=[]
odd=[]
even_counter=0
odd_counter=0

while i<=10:
    if i%2==0:
        even.append(i)
        even_counter+=1
    else:
         odd.append(i)
         odd_counter+=1
    i+=1
print(f"number of even={even} , number of even_counter={even_counter}")

print(f"number of odd={odd} , number of odd_counter={odd_counter}")

number of even=[0, 2, 4, 6, 8, 10] , number of even_counter=6
number of odd=[1, 3, 5, 7, 9] , number of odd_counter=5

In [ ]:
i=5
while i<=20:
    if i==10:
        break
    else:
        print(i)
        i+=1

In [20]:
i=5
while i<=20:
    i+=1#continue بتعمل skip--->i+=1
    
    if i==10:
        continue
    else:
        print(i)
        #لما الشرط يتحقق او لما continue تشتغل بيبطل انه يجمع واحد ولا اكنه شايفه ف بيفضل الكود مستمر 
        #while هتفضل ب true ولكل i مش هتزيد
        #continue---->بتعمل skip لاي counter بيتحط بعدها

6
7
8
9
11
12
13
14
15
16
17
18
19
20
21

In [ ]:
i=5
while i<=20:
    
    if i==10:
        i+=1#continue بتعمل skip--->i+=1
        continue
    else:
        print(i)

In [1]:
# definr function 
def greet():
    print("hello world")
greet()

hello worl

In [3]:
def greet(name):#name----> argument
    ##name----> argument انا هاخده من المستخدم لما يعمل call لل function
    print(f"hello {name}")
greet("basant") #basant---->parameter

hello basant

In [4]:
# name as input
n=input("enter you name:")
greet(n)
#function دي لازم تستقبل حاجة اي كان بقي مسمي ال variable

enter you name: bbbb

hello bbbb

In [5]:
def multiply(a,b):
    print(a*b)
multiply(3,4)

12

In [7]:
#a , b as input
n1=int(input("enter your frist number"))
n2=int(input("enter your second number"))
multiply(n1,n2)

enter your frist number 3
enter your second number 5

15

In [9]:
def add(a,b):
    print(a+b)
add(3,4)

7

In [10]:
n1=int(input("enter your frist number"))
n2=int(input("enter your second number"))
add(n1,n2)

enter your frist number 5
enter your second number 5

10

In [11]:
def add(a,b):#no output
    a+b
add(2,3)    #هي جمعت الرقمين عادي بس دي اله يعني محتاجة تقولها اطبعيلي

In [12]:
def addp(a,b):
   print( a+b)#diplay ---->result
addp(2,3)

5

In [13]:
def addR(a,b):
   return a+b#diplay ---->result
addR(2,3)  #رجعلي النتاج

5

In [16]:
#two option for diplay---> print or return
#print or return
#print---->بتطبع او بتظهره في ال سيستم مقدرش ساعاتها اني اخزنه في متغير تاني
#return---->بترجع الرقم اقدر اني اخزنه في متغير تاني


sum_print=addp(2,2)# 4 هتظهر ال 
#addp(2,2)---->اصلا فيها جملة print
#طب ليه لان ال function فيها جملة print فظهرتها مخزنتش
print(sum_print)#none 
#هي مخونتش اصلا حاجة علشان تطبعها
#بتعمل طباعه بس مقدرش اخزن القيمة بتاعتها في متغير تاني

4
None

In [ ]:
sum_return=addR(6,6)#11
#طبعت ال 11 علشان هي رجعت الرقم بمعني انها قيمة اتخنت عادي في متغير 
print(sum_return)#وطبعتها عن طريق جملة ال print دي
#return ---->قدرنا نخزن قيمتها في variable من خلال اني عملت call لل function وقدرت انده عليها اكتر من مرة
#هنستديعها اكتر من مرة من خلال المتغير وليس اني اعمل calling--->function

In [24]:
#function --->check even or odd
#check one number
def even_odd(n):
    if n%2==0:
        print(f"{n} is even")
    else:
        print(f"{n} is odd")

even_odd( 4)      
    #مفيش حاجة تلف علي ال list

In [26]:
#function --->check even or odd
#check list of numbers
def even_odd(lis):
    for i in lis:
        if i%2==0:
          print(f"{i} is even")
        else:
         print(f"{i} is odd")

even_odd([1])     #لازم input يكون list حتي لو فيها رقم 1 بس

1 is odd

In [4]:
def neg_pos(lis):
    for j in lis:
        if j>0:
            print(f"{j} is postive")
        else:
            print(f"{j} is negative")
n=map(int,input("enter list of numbers:").split()) 

neg_pos(n)

enter list of numbers: 1 2 3

1 is postive
2 is postive
3 is postive

In [5]:
def greet (name="hala"):# default value 
    #في حالة انك مابتصتش له اسم هو هيطبع  hello hala من نفسه بدل اما يطلعيلي error
    
    print(f"hello {name}")
greet()

hello hala

In [6]:
greet("ahmed")

hello ahmed

In [7]:
def info(name,age):
    print(f"your name is: {name}, your age is:{age}")
info("omar",3)

your name is: omar, your age is:3

In [8]:
#طب لو عكست مش هيفهم ان ده الاسم وده العمر 
info(3,"omar")

your name is: 3, your age is:omar

In [9]:
#ده الحل اني احددله انه الاسم وانهي العمر
#calling for argument 
#هتنادي علي argument(name,age)
info(age=3,name="omar")
#حتي لو عكستهم المهم اني عرفت انه الاسم عن طريق name
# وانهي العمر عن طريق age
#ده شكل ال error
#TypeError: info() missing 2 required positional arguments: 'name' and 'age'

your name is: omar, your age is:3

In [11]:
#في حالة بقي انك مش عارف اي هم ال arguments
#هتعمل call ليها فاضية هيطلع error في اسماء ال arguments
info()

TypeError: info() missing 2 required positional arguments: 'name' and 'age'

In [3]:
#لو عاوز استقبل عدد مالانهاية من الارقام علشان اجمعهم استخدم *
# *--->بتقولي انها تقدر تستقبل ارقاااااام كتتتير جدا
def add(*a):
    #a--->tuple
    print(a)
    #علشان لازم الارقام دي تتخزن عندي ودي مش رقم دي اكتر من رقم ف كاما لازم تتحزن في حاجة زي tuple
    #علشان tuple اسرع في التحزين الكمبيوتر بيسهل علي نفسه بيختار الاسرع والاخف عليه
    #حتي لو دخلت رقم واحد هيفضل نوعها tuple لان الكمبيوتر حافظ مش فاهم انت عرفته انا هدخل اكتر من رقم حالا
    #غير ان هتجمع واحد وبس لا لازم يبقي فيه رقم تاني
    print(type(a))
    return sum(a)

In [5]:
add(1)

(1,)
<class 'tuple'>

1

In [6]:
sum([1,2,3,4])#لازم ادي الدالة دي الارقام ك list 
#علشان كده عملت الطريقة اللي فوق
#def add(*a):== sum([1,2,3,4])
#زي ما تقول كده حطيت ال list دي في متغير وبصيت له بقي

10

In [7]:
#المتوسط= مجموعهم علي عددهم
def average(*a):
    Sum=sum(a)#المجموع
    num_len=len(a)#العدد
    return Sum/num_len


average(1,2,3,4,5)    
#*a--->هو كده فيهم ان ال input اللي هتستقبلها هتستقبلها في tuple

3.0

In [11]:
def full_name(*name):
   for i in name: 
    print(i)#لف علييها واطبع كل واحدة لوحدها
#*a---->بخزنله قيم مختلفة string ,int ,float في نفس الوقت عادي   
#*------>tuple

In [12]:
full_name("basant","shaker")

bbbb
aaaa

In [4]:
#**---->مش بتتعامل معاه ك tuple بتتعامل معاه ك dictionary
#**----->dictionary
def info(**x):
    
    print(x)
info(name="basant",age=25) 
#name--->key
#"basant"--->value

dict_items([('name', 'basant'), ('age', 25)])

In [5]:
#**---->مش بتتعامل معاه ك tuple بتتعامل معاه ك dictionary
#**----->dictionary
def info(**x):
    
    print(x.items())
info(name="basant",age=25) 
#name--->key
#"basant"--->value

dict_items([('name', 'basant'), ('age', 25)])

In [8]:
def info(**info):
    for key,value in info.items():#لفيلي عليها كانها list قيم وانا بجيبها
        print(f"{key} : {value}")
info(name="basant",age=25)    
#.items() هي اللي بتسمح لـ for loop أنها تدخل جوه الـ Dictionary وتجيب الحاجتين مع بعض

name : basant
age : 25

In [12]:
def info(**info):
  for key,value in info:
    print(key) 
# الناتج هيكون المفاتيح بس:
# name
# age
info(name="basant",age=25)   
#بتقولك انا مش معايا غير key وانت طالب مني اكتر من حاجة ف في مثل يقولك(اطبخي يا جارية كلف يا سيدي)
#بمعني متطلبش مني حاجة اانا مش هعرف اني اجيبهالك
#هنا طالبة منها تديني ال key ,value وانا مش مدياها غير ال key بس
#.item()--->خشيلي جوه هاتلي القميتن بقي حالا شايفها

ValueError: too many values to unpack (expected 2)

In [1]:
#recursion ---->كأن الدالة بتنادي علي نفسها 
#هي مش loop هي function جوه function جوه function
#             5
def factorial(num):#paramter 
    if num==0 or num==1:
        return 1#استخدمنا return علشان يقدر انه يخون القيمة 
    else:
        return num*factorial(num-1)
# step1 ----> 5*fac(4)
# step2 ----> 5*4*fac(3)
# step3 ----> 5*4*3*fac(2)
# step3 ----> 5*4*3*2*fac(1)
# step3 ----> 5*4*3*2*1
#مقلش صفر لانه وقف لحد 1

In [2]:
factorial(5)

120

In [18]:
#تدخل رقم ويعملهولك بشكل تنازلي 
def count_down(n):
    if n==0:
        return 1 
    else:
        print(n)
        return count_down(n-1)

In [13]:
count_down(10)

10
9
8
7
6
5
4
3
2
1

In [20]:
#تدخل رقم ويعملهولك بشكل تنازلي 
def count_down(n):
    if n==0:
        return 1 
    else:
        print(n)
        count_down(n-1)
count_down(10)

10
9
8
7
6
5
4
3
2
1

In [23]:
#lamdaa function 
#مشكلتها انها بسيطة يعني مش بقدر اكتب فيها تفاصيل كتير بقي وتعقيدات زي ال function العادية
#ال function اللي قبل كده كانت معقدة وبتتكتب علي اكتر من سطر 
#لكن انا عاوزة اكتب ال function علي سطر واحد
#sum1 --->name function
#lambda x,y---->هتستقبل قيمتين
#: x+y --->return x+y
sum1=lambda x,y : x+y
sum1(1,2)

3

In [24]:
def sum2(x,y):
      return x+y
sum2(2,3)

5

In [25]:
multiply=lambda x,y : x*y
multiply(2,2)

4

In [27]:
power=lambda base,power:base**power
power(2,3)#2^3=8

8

In [29]:
prices=[100,200,300]
list(map(lambda x:x*0.1,prices))

[10.0, 20.0, 30.0]